name: Terraform CI-CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform CI-CD
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      # 3. Install Terraform
      - name: Install Terraform
        run: |
          TERRAFORM_VERSION="1.14.6"
          wget -q "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
          unzip -o "terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
          sudo mv terraform /usr/local/bin/terraform

      # 4. Verify Terraform
      - name: Terraform Version
        run: terraform version

      # 5. Terraform Init
      - name: Terraform Init
        working-directory: "Parent module"
        run: terraform init -input=false

      # 6. Terraform Format
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # 7. Terraform Validate
      - name: Terraform Validate
        working-directory: "Parent module"
        run: terraform validate

      # 8. Terraform Plan
      - name: Terraform Plan
        working-directory: "Parent module"
        run: terraform plan -input=false -var-file="terraform.tfvars"

      # 9. Terraform Apply
      - name: Terraform Apply
        working-directory: "Parent module"
        run: terraform apply -input=false -auto-approve -var-file="terraform.tfvars"