name: Terraform CI

on:
  push:
    branches:
      - main

jobs:
  terraform-ci:
    name: Terraform CI
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      # 3. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      # 4. Terraform Init
      - name: Terraform Init
        working-directory: "Parent module"
        run: terraform init

      # 5. Terraform Format Check
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # 6. Terraform Validate
      - name: Terraform Validate
        working-directory: "Parent module"
        run: terraform validate

      # 7. Terraform Plan
      - name: Terraform Plan
        working-directory: "Parent module"
        run: terraform plan -var-file="terraform.tfvars"